// <auto-generated />
namespace CU.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Schema1a_addLookups : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Schema1a_addLookups));
        
        string IMigrationMetadata.Id
        {
            get { return "202205181548401_Schema1a_addLookups"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
